server {
    listen 80;

    # Serve static landing page
    location = / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location = /index.html {
        root /usr/share/nginx/html;
    }

    # Forward EVERYTHING else to Tomcat
    location / {
        proxy_pass http://ezev_app:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
